// <auto-generated />
using System;
using BookTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519094529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000001"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000002"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000003"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000004"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000005"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000005")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000006"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000006")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000007"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000007")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000008"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000008")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000009"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000009")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000010"),
                            AuthorId = new Guid("00000000-0000-0000-0002-000000000010")
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000001"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000002"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000003"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000003"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000006")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000003"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000004"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000004"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000005"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000005"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000008")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000006"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000006"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000007")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000007"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000005")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000007"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000008"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000008")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000008"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000009"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000009"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000010"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000010"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("00000000-0000-0000-0001-000000000010"),
                            GenreId = new Guid("00000000-0000-0000-0003-000000000008")
                        });
                });

            modelBuilder.Entity("BookTrack.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Bio = "American author of epic fantasy.",
                            FirstName = "Patrick",
                            LastName = "Rothfuss"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Bio = "American author known for hard science fiction.",
                            FirstName = "Andy",
                            LastName = "Weir"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Bio = "New York Times bestselling author of cozy fantasy.",
                            FirstName = "TJ",
                            LastName = "Klune"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Bio = "USA Today and Wall Street Journal bestselling author.",
                            FirstName = "Rebecca",
                            LastName = "Yarros"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Bio = "American author and creative director.",
                            FirstName = "Bonnie",
                            LastName = "Garmus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Bio = "English author, screenwriter, and humorist.",
                            FirstName = "Douglas",
                            LastName = "Adams"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Bio = "English novelist known for her romantic fiction.",
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Bio = "British author for children and adults.",
                            FirstName = "Matt",
                            LastName = "Haig"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Bio = "New York Times and internationally bestselling author.",
                            FirstName = "Sarah J.",
                            LastName = "Maas"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Bio = "American author of contemporary fiction.",
                            FirstName = "Taylor Jenkins",
                            LastName = "Reid"
                        });
                });

            modelBuilder.Entity("BookTrack.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AverageRating = 4.5499999999999998,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
                            Description = "A young man grows to be the most notorious wizard his world has ever seen, told in his own words.",
                            Isbn = "9780756404741",
                            PageCount = 662,
                            PublishedYear = 2007,
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AverageRating = 4.5199999999999996,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
                            Description = "A lone astronaut must save the Earth from disaster in this propulsive science-fiction adventure.",
                            Isbn = "9780593135204",
                            PageCount = 476,
                            PublishedYear = 2021,
                            Title = "Project Hail Mary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            AverageRating = 4.2599999999999998,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781250217288-L.jpg",
                            Description = "A magical story about love, family, and what makes a person good or evil.",
                            Isbn = "9781250217288",
                            PageCount = 394,
                            PublishedYear = 2020,
                            Title = "The House in the Cerulean Sea"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            AverageRating = 4.1699999999999999,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781649374042-L.jpg",
                            Description = "In a world where dragons choose their riders, one girl must survive the most dangerous year of her life.",
                            Isbn = "9781649374042",
                            PageCount = 517,
                            PublishedYear = 2023,
                            Title = "Fourth Wing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            AverageRating = 4.0599999999999996,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780385547345-L.jpg",
                            Description = "A female scientist becomes America's most beloved cooking show host in 1960s California.",
                            Isbn = "9780385547345",
                            PageCount = 390,
                            PublishedYear = 2022,
                            Title = "Lessons in Chemistry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            AverageRating = 4.2199999999999998,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
                            Description = "Seconds before the Earth is demolished for a bypass, Arthur Dent is swept into a madcap tour of the universe.",
                            Isbn = "9780345391803",
                            PageCount = 193,
                            PublishedYear = 1979,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            AverageRating = 4.2800000000000002,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                            Description = "The beloved story of Elizabeth Bennet and the proud Mr. Darcy in Regency England.",
                            Isbn = "9780141439518",
                            PageCount = 432,
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            AverageRating = 3.9900000000000002,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
                            Description = "Between life and death lies the Midnight Library — a place to try all the lives you could have lived.",
                            Isbn = "9780525559474",
                            PageCount = 304,
                            PublishedYear = 2020,
                            Title = "The Midnight Library"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            AverageRating = 4.1500000000000004,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781635575569-L.jpg",
                            Description = "A young mortal girl is whisked away to a magical land where the stakes are much higher than she imagined.",
                            Isbn = "9781635575569",
                            PageCount = 419,
                            PublishedYear = 2015,
                            Title = "A Court of Thorns and Roses"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            AverageRating = 4.4199999999999999,
                            CoverImageUrl = "https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg",
                            Description = "Reclusive Hollywood legend Evelyn Hugo finally reveals the truth about her glamorous and scandalous life.",
                            Isbn = "9781501161933",
                            PageCount = 389,
                            PublishedYear = 2017,
                            Title = "The Seven Husbands of Evelyn Hugo"
                        });
                });

            modelBuilder.Entity("BookTrack.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Name = "Classic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Name = "Cozy Fantasy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Name = "Literary Fiction"
                        });
                });

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.HasOne("BookTrack.Domain.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookTrack.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookTrack.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookTrack.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
