// <auto-generated />
using System;
using BookTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520000000_AddUserBookRating")]
    partial class AddUserBookRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookTrack.Domain.Entities.UserBook", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("AddedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("BookId").HasColumnType("uuid");
                    b.Property<int?>("Rating").HasColumnType("integer");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("BookId");
                    b.HasIndex("UserId", "BookId").IsUnique();
                    b.ToTable("UserBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
